on:
  workflow_dispatch:


jobs:
  job1:
    runs-on: self-hosted
    steps:
      - run: |
          echo "::group::Environment Info"
          space=$(df . -h)
          printf "Currently working inside %s\n" "${PWD}"
          printf "Data on space: \n%s" "${space}"
          echo "::endgroup::"
      - run: |
          echo "hello there!"
